package com.example.appajicolorgrupo4.ui.theme

import androidx.compose.ui.graphics.Color

/**
 * Paleta de colores disponibles para camisetas de adulto.
 * Estos colores serán utilizados en el catálogo de productos.
 *
 * Nota: Algunos nombres contienen caracteres especiales (tildes) que son válidos en Kotlin.
 */

// Colores para camisetas de adulto
@Suppress("unused")
val Negro = Color(0xFF000000)
@Suppress("unused")
val Carbón = Color(0xFF4D4D4D)
@Suppress("unused")
val GrisJaspe = Color(0xFFB8B8B8)
@Suppress("unused")
val Plata = Color(0xFFCCCCCC)
@Suppress("unused")
val Blanco = Color(0xFFFFFFFF)
@Suppress("unused")
val Arena = Color(0xFFF1E8BF)
@Suppress("unused")
val Beige = Color(0xFFCCBC8E)
@Suppress("unused")
val Chocolate = Color(0xFF502D19)
@Suppress("unused")
val Marrón = Color(0xFF6F1D3F)
@Suppress("unused")
val Ladrillo = Color(0xFF8A1523)
@Suppress("unused")
val Ocre = Color(0xFFCF6127)
@Suppress("unused")
val Rojo = Color(0xFFBB1535)
@Suppress("unused")
val Naranja = Color(0xFFF16324)
@Suppress("unused")
val Mango = Color(0xFFFAA71A)
@Suppress("unused")
val Canario = Color(0xFFFFDF22)
@Suppress("unused")
val Lima = Color(0xFFB6D25B)
@Suppress("unused")
val Jade = Color(0xFF08815E)
@Suppress("unused")
val Olivo = Color(0xFF65543A)
@Suppress("unused")
val VerdeBosque = Color(0xFF004634)
@Suppress("unused")
val Marino = Color(0xFF1F2C60)
@Suppress("unused")
val Delfín = Color(0xFF2C456E)
@Suppress("unused")
val Royal = Color(0xFF184791)
@Suppress("unused")
val Turquesa = Color(0xFF29AEC2)
@Suppress("unused")
val Celeste = Color(0xFF5E99CC)
@Suppress("unused")
val AzulClaro = Color(0xFFBAD4E8)
@Suppress("unused")
val Aqua = Color(0xFFC4EADF)
@Suppress("unused")
val RosaPastel = Color(0xFFF3C6D0)
@Suppress("unused")
val Coral = Color(0xFFF38274)
@Suppress("unused")
val Fucsia = Color(0xFFD21879)
@Suppress("unused")
val Morado = Color(0xFF40306B)
